### ISSUE TITLE
Play with Ubuntu

### ISSUE THREAD

**Issue by U-lis** [BravePeach/bravepeach_web#1]
[Virtualbox](https://www.virtualbox.org/) 를 이용해 [Ubuntu 16.04.1 LTS](https://www.ubuntu.com/) 를 설치하고 우분투의 첫 맛을 느껴본다.

### 익숙해져야 하는 CLI(terminal) 명령어
0. sudo
1. apt // apt-get
2. cd (dir_name)
3. mkdir (dir_name)
4. rm (file_name)
5. mv (origin) (destination)
6. cp (origin) (destination)
7. rm -rf (target) **Danger!**
8. ./(executable)

### 자주 사용하게 될 것들
1. curl // wget
2. ssh
3. scp
4. git
5. vim // nano(?) // emacs(??)

**Comment by MoonHyuk** [comment]
우분투 설치 완료

**Comment by U-lis** [comment]
`이것이 우분투 리눅스다` 책은 아래 챕터를 우선적으로 보시면 됩니다.
- chapter 1: 이미 설치하셨을테니 건너뛰어도 무방할듯
- chapter 4, 7, 8-2
- chapter 11-1, 11-2 (DB)
