### ISSUE TITLE
Read pro git book / git flow

### ISSUE THREAD

**Issue by U-lis** [BravePeach/bravepeach_web#3]
[pro git book](https://git-scm.com/book/ko/v2) 의 2, 3장과 [git-flow cheatsheet](http://danielkummer.github.io/git-flow-cheatsheet/index.ko_KR.html) 의 내용을 읽고 숙지한다.
특히 branch가 어떻게 작동하는지에 대해 이해한다.

**Advance**
1. #1 에서 설치한 ubuntu에 git을 설치하고 https://github.com/U-lis/initial-settings.git 를 클론받아본다.
2. 위에서 클론받은 폴더에 들어가 git flow를 활성화시켜본다.

**Comment by MoonHyuk** [comment]
특이사항

1. 가상머신 위에서 우분투 네트워크 연결이 안되어 네트워크 설정을 NAT로 바꾸니 해결되었습니다.

2. 터미널에서 sudo apt-get install git-all 명령을 치니 아래와 같은 오류가 났습니다.

<img width="732" alt="2017-02-14 4 54 51" src="https://cloud.githubusercontent.com/assets/22232561/22920035/5a3cc25e-f2d6-11e6-96cd-a97412bed208.png">

이 오류는 [이곳](http://askubuntu.com/questions/654951/failed-to-connect-to-socket-com-ubuntu-upstart-connection-refused-errors-were)을 참고하여 해결되었습니다. 대한님도 혹시 오류가 생기면 참고하시기 바랍니다.

현재 우분투에 깃을 설치하는데 까지 진행되었습니다.

**Comment by U-lis** [comment]
깃을 설치하는 명령은 `sudo apt install git` 이면 충분합니다.

**Comment by MoonHyuk** [comment]
앗 네 감사합니다

**Comment by U-lis** [comment]
![merge_rebase](https://cloud.githubusercontent.com/assets/3654082/22920466/86c1ffd6-f2d8-11e6-998c-1b826ae9799a.png)
질문을 받았기에 merge와 rebase의 차이에 대해 간단하게 샘플을 만들어보았습니다.

**Comment by MoonHyuk** [comment]
한번 정독하였습니다. 내일 아침에 다시 복습해봐야 할것 같습니다.

**Comment by U-lis** [comment]
#8 을 진행하면서 같이 실습할 예정.
