### ISSUE TITLE
Install pycharm, make django app

### ISSUE THREAD

**Issue by U-lis** [BravePeach/bravepeach_web#4]
#1 에서 설치한 Ubuntu에 pycharm을 설치하고 적당한 곳에 django tutorial을 할만한 곳을 만든다.

1. pycharm을 위한 자바 설치
2. pycharm 다운로드, 실행
3. 터미널에서 적당한 곳에 tutorial 폴더 생성
4. tutorial 폴더 안에서 venv 생성, 활성화
5. pip를 이용해 django 설치

**Note**: [장고걸스](https://tutorial.djangogirls.org/ko/) 참조

**Comment by MoonHyuk** [comment]
완료했습니다. 

0. `sudo apt install python3-dev python3-pip`

1.  `sudo apt-get install default-jre`

2. `sudo add-apt-repository ppa:mystic-mirage/pycharm`
`sudo apt-get update`
`sudo apt-get install pycharm-community` //커뮤니티 버전
`sudo apt-get install pycharm` //professional 버전

3. `mkdir python-example`
`cd python-example`


4. `pip3 install virtualenv`
`virtualenv venv` //가상환경 생성 
`source venv/bin/activate`//활성화

5. `pip3 install django`

**Comment by U-lis** [comment]
@DaehanKim 님도 실제로 한번 해보시고 다 완료되면 이슈 닫아주세요
